### ISSUE TITLE
Unable to bind parameters in raw SQL query

### ISSUE THREAD

**Issue by christian-mibex** [ForestAdmin/agent-nodejs#1056]
## Expected behavior

I want to insert using a native query to use more advanced SQL functionality e.g.

```typescript
const insert = "INSERT INTO applications (name, key, vendor, vendorId) VALUES ($1,$2,$3,$4) ON CONFLICT (key) DO UPDATE SET name = $1, vendor = $3, vendorId = $4;";
await someCollection.nativeDriver.rawQuery(insert, [name, key, vendor, verndorId]);
```

I expect this query to succeed because the type of  [rawQuery](https://github.com/ForestAdmin/agent-nodejs/blob/27bbba0542351c59fa15d9fb8beb8657c5971409/packages/datasource-sequelize/src/collection.ts#L51) is [BindOrReplacements](https://github.com/sequelize/sequelize/blob/79111f0/packages/core/src/sequelize.d.ts#L523) which can be an array like above.

## Actual behavior

With the current implementation of `rawQuery` the call fails because the parameters are not forwarded correctly here:
```typescript
rawQuery: async (sql: string, replacements: BindOrReplacements) => {
  const result = await model.sequelize.query(sql, {
    type: QueryTypes.RAW,
    plain: false,
    raw: true,
    replacements,
  });
```

In my example it should be `bind: replacements,` and for the [replacement syntax](https://sequelize.org/docs/v6/core-concepts/raw-queries/#replacements) it needs to be `replacements: replacements`.

Not sure what the best way is to solve this. I imagine something like:

```typescript
interface Bind {
  bind: BindOrReplacements
}

interface Replacement {
  replacements: BindOrReplacements
}

rawQuery: async (sql: string, replacements: Bind | Replacement) => {
  const result = await model.sequelize.query(sql, {
    type: QueryTypes.RAW,
    plain: false,
    raw: true,
    ...replacements,
  });
``` 
This pushes the decision to the user, with the downside of a not-so-clear api.

## Failure Logs

The parameters are not included:
```
 error: there is no parameter $1
```

## Context

- Package Version: main branch

**Comment by DayTF** [comment]
Hello @christian-mibex 👋 

I understand your confusion as the name of the type is BindOrReplacements, they have the same definition but the `rawQuery` function only supports replacements. I will rename the type and add some JSDoc so it can be more clear.

Sadly the direction you have suggested would not be possible as it would be breaking for all current usages and we do not consider this as enough of a reason to introduce a new major version.

I will create a task to add an option, allowing the use of bind.
In the meantime, I suggest you to use [replacements](https://sequelize.org/docs/v6/core-concepts/raw-queries/#replacements).

**Comment by DayTF** [comment]
Fix for the typing name and JSDoc has been released #1060 
I have created a feature PR to allow the use of bind parameters via an option, it has yet to undergo review/validation #1062

**Comment by christian-mibex** [comment]
Hi @DayTF thanks for looking into it.

Indeed, the replacements work! 

Even if I like the bind syntax better because of positional unnamed params, I think it is good enough with the improved docs. 

Maybe you can add a remark about the restriction here as well? https://docs.forestadmin.com/developer-guide-agents-nodejs/data-sources/getting-started/queries#querying-with-the-native-driver

That would have saved me (and you) some time

**Comment by DayTF** [comment]
The support for bind parameters has been merged, you can expect the release to be available in a few minutes.

Thanks for your feedback!
