### ISSUE TITLE
Smart-action submit button

### ISSUE THREAD

**Issue by nike1v** [ForestAdmin/agent-nodejs#1158]
## Expected behavior

There are a field that allows change the text value of submit button

## Actual behavior

The submit button inherits the name of the smart-action

## Context

Is it possible to change the button text and smart-action form name separately?

- Package Version: latest

**Comment by DayTF** [comment]
Hello @nike1v,

There is currently no way for the user to change the label of the submit button inside of an action form.
The label is by default the display name of the action, if the frontend detects that the action requires an [approval](https://docs.forestadmin.com/user-guide/other-tabs/collaboration/approval-requests) or might have a [conditional approval](https://docs.forestadmin.com/user-guide/project-settings/teams-and-users/manage-roles#collection-permissions), the label then becomes `Request approval`.

**Comment by nike1v** [comment]
Ok, thanks, I got it, hope it will be an option to change it in the future!
