### ISSUE TITLE
Last SQL datasource version broke everything about timestamps

### ISSUE THREAD

**Issue by Segfaultd** [ForestAdmin/agent-nodejs#1168]
Hi,

We have just upgraded our version of `@forestadmin/datasource-sql` from `1.14.14` to `1.14.16`.
Regenerating the schema had for effect to remap every `created_at` to `createdAt` and `updated_at` to `updatedAt` in the JSON.

Obviously, the camelCase version of the field do not exist in the database, and thus every collection impacted is fully broken in the ForestAdmin UI, with a call returning a `SequelizeDatabaseError` => `Unexpected error`.

Hotfix was to rollback to previous version, and regenerate schemas.

This PR is probably the root cause: https://github.com/ForestAdmin/agent-nodejs/pull/1165

Not serious.

**Comment by DayTF** [comment]
Hello @Segfaultd, thanks for your report.

We are currently deploying a revert, sorry for the inconvenience.
