### ISSUE TITLE
Feature request: reformat a field

### ISSUE THREAD

**Issue by Segfaultd** [ForestAdmin/agent-nodejs#461]
## Expected behavior

Would be nice to be able to reformat a field "on-the-fly". Something like this

```
collection.reformatField('created_at', (field) => {
    return (field as Date).getDay();
});
```

## Actual behavior

This would return a field on a newer format

**Comment by romain-gilliotte** [comment]
Hi segfaultd

Sadly that would not work with just a handler.

You would need to provide at least:
- The new type of the field after transformation
- The transformation method to go the other way, otherwise you would break writing
- Filter rewriting (the underlying database can't automatically undo the transformation to filter)
- Sorting

If you don't need neither of those features, you can do the following:
```
collection
  .addField('created_at_new', {
    columnType: 'Number',
    dependencies: ['created_at'],
    getValues: records  => records.map(r => (field as Date).getDay())
  })
  .removeField('created_at')
  .renameField('created_at_new', 'created_at')
```

**Comment by romain-gilliotte** [comment]
Also, I see that you have a cast in your code.

Did you setup the typing generation?
You really should! It helps a ton when building an agent

https://docs.forestadmin.com/beta-developer-guide-agents-v2/getting-started/install/autocompletion-and-typings

**Comment by romain-gilliotte** [comment]
As of today, our CSV exporter is not customizable in any way (it's a feature from the early days of the company).

You can generate files from smart actions (if generating a big CSV, you can provide a stream to the `resultBuilder`)

https://docs.forestadmin.com/beta-developer-guide-agents-v2/agent-customization/actions/responses#file-generation

```
collection.addAction('Export Data', {
  scope: 'Global',
  generateFile: true,
  execute: async (context, resultBuilder) => {
    return resultBuilder.file('StringThatWillBeInTheFile', 'filename.csv', 'application/csv');
  },
});
```

You can then remove the default export from the frontend using Roles

https://docs.forestadmin.com/user-guide/project-settings/teams-and-users/manage-roles

**Comment by Segfaultd** [comment]
Make sense! Thank you @romain-gilliotte
