### ISSUE TITLE
Issue with subdocuments and JSON editor

### ISSUE THREAD

**Issue by john-evan08** [ForestAdmin/agent-nodejs#513]
## Expected behavior
<img width="500" alt="Screenshot 2022-10-25 at 16 06 55" src="https://user-images.githubusercontent.com/44803336/197795769-5c9df28a-2eca-4988-a088-e2230c386bda.png">

I have a mongoose schema with subdocuments containing subdocuments. (level = 3)
When there is just one level of subdocuments, the first level estimate sub field type and put default widget on it. ✅

## Actual behavior
But in my case (3 levels), forest admin just set a json editor widget to edit it. 
How to flatten the nested subdocuments so I can see them in related data with the suitable widgets ?

## Failure Logs
Here is my JSON view in forest admin whereas I want the "blocks" to be in related data.
<img width="338" alt="Screenshot 2022-10-25 at 16 09 46" src="https://user-images.githubusercontent.com/44803336/197797482-9319daaf-3246-4185-9ebf-9ff1450d1602.png">

## Context

- Package Version:
- "@forestadmin/agent": "^1.1.4",
- "@forestadmin/datasource-mongoose": "^1.0.2",

**Comment by jeffladiray** [comment]
Hello @john-evan08 :wave:

You should be able to use our `asModel` option to flatten nested fields within a mongoose model (See [this documentation](https://docs.forestadmin.com/developer-guide-agents-nodejs/data-sources/provided-datasources/mongoose#dealing-with-deeply-nested-models))

Let me know if that helps

**Comment by john-evan08** [comment]
Hello @jeffladiray , 

Thanks for your quick answer.

Firstly, I tried your "asModel" solution but the .forestadmin_schema doesn't update. Do you know why ?
![Screenshot 2022-10-25 at 17 26 05](https://user-images.githubusercontent.com/44803336/197816235-be61544b-ca75-49b5-b7ff-651feccf1543.png)

Then, my ideal solution would be to have my nested subdocuments in related data, as in the following screenshot.
<img width="809" alt="Screenshot 2022-10-25 at 17 26 50" src="https://user-images.githubusercontent.com/44803336/197816653-ee3be487-2f95-4bdc-a1f4-edda373b96ab.png">

But Indeed if I can have my subdocuments in another collection like it's done with asModel (if I make it work), it will be okay !

**Comment by jeffladiray** [comment]
Good to know :)

I'm closing the issue then.

In the future, don't hesitate to go to [our community](https://community.forestadmin.com/) if you encounter any issues or if you have any questions. We tend to answer a bit faster there 👍
