### ISSUE TITLE
Cant filter collection where UUID is not defined

### ISSUE THREAD

**Issue by ajubin** [ForestAdmin/agent-nodejs#568]
## Expected behavior

Hi, I've got the following schema (simplified)

A one to many relationship between "User" and "CustomerSuccessManager" (simplified in CSM)
- a User has a CSM associated
- a CSM can manage many user

```
User {
id: uuid
csmId: uuid | undefined
}

CSM {
id: uuid
email:string
}
```

On forest admin panel, I want to filter all User without CSM like this.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/14874974/206750316-9dcb7d13-613e-4286-af61-40483cd3f58c.png">

This causes an error.

As a workaroud, I can filter on other field.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/14874974/206750472-f5549a13-3593-4411-8eac-a8a36ecb9742.png">

## Failure Logs

The server fails due to the following incorrect sql query.

```sql
SELECT
    "user"."id",
    "customerSuccessManager"."email" AS "customerSuccessManager.email",
    "customerSuccessManager"."id" AS "customerSuccessManager.id"
    FROM "user" AS "user"
    LEFT OUTER JOIN "core_team_member" AS "customerSuccessManager" ON "user"."customerSuccessManagerId" = "customerSuccessManager"."id"
WHERE (
        "customerSuccessManager"."id" IS NULL
        OR "customerSuccessManager"."id" = '' -- this introduce the bug
    )
ORDER BY
    "user"."createdAt" DESC
LIMIT 15
OFFSET 0;
``` 

the error is 

```
ERROR:  invalid input syntax for type uuid: ""
LINE 9:         OR "customerSuccessManager"."id" = ''
```

Indeed, psql cannot cast `''` into a string.

## Possible solutions

After digging into the source code with the debugger, here the exact line causin the bug in the method `makeWhereClause(field, operator, value)`
https://github.com/ForestAdmin/agent-nodejs/blob/00d62003da56e0ef3ac922d22b9e5eea334b1350/packages/datasource-sequelize/src/utils/query-converter.ts#L56

it adds this into the query ` { [Op.eq]: '' }` .

### Option 1: detect if field is a uuid
To fix this, it would be great to detect if the field is a uuid and remove this field in this case.

But accessing the field type is a bit hacky here.
The params available in this method are 

```
field: 'customerSuccessManager.id'
operator: 'Blank'
value: null

this.dialect = 'postgres'
this.model.associations.customerSuccessManager.target.fieldRawAttributesMap.id.type = 'UUID'
```

### Option 2: detect if field is a uuid outside this function

Pass type of field  to `makeWhereClause` and add a condition if type === 'UUID'

### Option3: cast equality to text

To change the above query line from `OR "customerSuccessManager"."id":= ''` to  `OR "customerSuccessManager"."id"::text = ''`

But I don't know the impact elsewhere

### Option4: remove the condition 

But I don't know the impact elsewhere

## Context

```
├── @forestadmin/agent@1.4.5
├── @forestadmin/datasource-sql@1.1.4
├── @forestadmin/datasource-toolkit@1.1.1
```

**Comment by romain-gilliotte** [comment]
Hello!

I added a PR to close this one + a couple of others I found in the way (currently in review)

**Comment by romain-gilliotte** [comment]
This should work as expected now

**Comment by ajubin** [comment]
Thanks, it works 👍
