### ISSUE TITLE
datasource-toolkit/type validation EmptyArray and ArrayOfStrings causing issues

### ISSUE THREAD

**Issue by ajubin** [ForestAdmin/agent-nodejs#577]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@forestadmin/datasource-toolkit@1.1.1` for the project I'm working on.

I had 2 problems, so I added 2 conditions.

The first problem is when a smart segment returns an empty array, it triggers a HTTP error 500 because "EmptyArray" is not allowed for "Array" type

And the second problem, I tried to modify a JSON string with the following entry that is valid for JSON `["email"]`.
The detected type of this input was `ArrayOfString` which was not recognized as `Json` type.

Here is the diff that solved my problem, I know this is not perfect, the problem should reside on the type validation part

```diff
diff --git a/node_modules/@forestadmin/datasource-toolkit/dist/src/validation/field.js b/node_modules/@forestadmin/datasource-toolkit/dist/src/validation/field.js
index b9c67c0..ffab4b9 100644
--- a/node_modules/@forestadmin/datasource-toolkit/dist/src/validation/field.js
+++ b/node_modules/@forestadmin/datasource-toolkit/dist/src/validation/field.js
@@ -48,6 +48,16 @@ class FieldValidator {
             return;
         }
         const type = type_getter_1.default.get(value, schema.columnType);
+        // When no results is returned by a smart segment, it causes a crash
+        if (type === 'EmptyArray' && allowedTypes.some(type => type.includes('Array'))) {
+            allowedTypes.push(type)
+        }
+
+        // We encouter a bug here, the JSON we entered was an array ["email1"] but was not allowed even if it was valid json
+        if (type === 'ArrayOfString' && allowedTypes.includes('Json') ) {
+            allowedTypes.push('ArrayOfString')
+        }
+        
         if (allowedTypes && !allowedTypes.includes(type)) {
             throw new errors_1.ValidationError(`Wrong type for "${field}": ${value}. Expects ${allowedTypes}`);
         }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by romain-gilliotte** [comment]
Thank you!

I have a opened a bug in our internal tracker.
I'll work on that today

**Comment by romain-gilliotte** [comment]
this should be fixed

**Comment by ajubin** [comment]
Thanks, it works 👍
