### ISSUE TITLE
datasource-sequelize: filter "does not contains" is not working with postgresql

### ISSUE THREAD

**Issue by ajubin** [ForestAdmin/agent-nodejs#600]
## Expected behavior

On a collection, I want to filter all records where a field is not containing a given text.

In my specific case, I want to see all users not having "gmail.com" in their "email". But I encounter an HTTP 500 error code.

##  Workaround with `patch-package`

```
diff --git a/node_modules/@forestadmin/datasource-sequelize/dist/utils/query-converter.js b/node_modules/@forestadmin/datasource-sequelize/dist/utils/query-converter.js
index 5873873..5816fc3 100644
--- a/node_modules/@forestadmin/datasource-sequelize/dist/utils/query-converter.js
+++ b/node_modules/@forestadmin/datasource-sequelize/dist/utils/query-converter.js
@@ -42,7 +42,9 @@ class QueryConverter {
             case 'ILike':
                 return this.makeLikeWhereClause(field, value, false);
             case 'NotContains':
-                return { [sequelize_1.Op.not]: this.makeLikeWhereClause(field, `%${value}%`, true) };
+                // Dirty fix due to a crash when filtering a textual text not containing an input substring with postgresl
+                // Without this fix, this use case crash: try to filter out all users where email doesn't contain "gmail"
+                return { [sequelize_1.Op.notILike]:  `%${value}%` };
             // Arrays
             case 'IncludesAll':
                 return { [sequelize_1.Op.contains]: Array.isArray(value) ? value : [value] };
```

Without the fix, the `queryConverter.makeWhereClause` returns `{[not]: {[like]: "%muzzo%"}}` whereas it should return `{[notILike]: "%muzzo%"}`

## Context

- Package Version: datasource-sequelize 1.2.5

**Comment by jeffladiray** [comment]
I'm able to reproduce this bug on my end as well. I'll open a ticket in our internal issue tracker.

Thanks for reporting this :pray:

**Comment by SkyHuss** [comment]
Thanks again for reporting this bug 🙏, we just released the fix on the contain this morning

**Comment by jeffladiray** [comment]
I'm closing this as the fix is considered merged on our end. Don't hesitate to re-open the issue if needed.
