### ISSUE TITLE
Any way to get deleted record(s) in a Before/After Delete hook?

### ISSUE THREAD

**Issue by samtgarson** [ForestAdmin/agent-nodejs#607]
## Expected behavior

From what I can tell the [Delete contexts](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/datasource-customizer/src/decorators/hook/context/delete.ts) (for both Before and After hooks) are not given access to the record(s) that are about to be/have been deleted.

## Actual behavior

I'd expect to be able to access these (or their IDs), my use case is to be able to delete images in S3 when a record is deleted.

**Comment by jeffladiray** [comment]
Hey :wave:


[Before Delete Hook Context](https://forestadmin.github.io/agent-nodejs/classes/_forestadmin_datasource_customizer.HookBeforeDeleteContext.html)  should provide `filter` that allows you to retrieve the record that is about to be deleted. At that point in the stack, the database should be called yet, so the record wasn't retrieve.

[After Delete Hook Context](https://forestadmin.github.io/agent-nodejs/classes/_forestadmin_datasource_customizer.HookAfterDeleteContext.html) doesn't provide the record as it is supposed to be deleted at this point.

It was a choice during the implementation, as most of the driver we currently have do not always provide the record when removing records in the database.

Let me know if that helps

**Comment by samtgarson** [comment]
The filter from the before hook works great, thanks so much for the quick response.

The docs are generally amazing but I think it would be great to have a little more on this, particularly maybe some detail on what each of the things inside the hook context can be used for.
