### ISSUE TITLE
Sorting dynamic dropdown options?

### ISSUE THREAD

**Issue by samtgarson** [ForestAdmin/agent-nodejs#610]
## Expected behavior

Is it possible to sort the options in a dynamic Dropdown field type?
![image](https://user-images.githubusercontent.com/6242344/214824867-242b2272-adac-4f6e-91f5-0d04fea81615.png)

I would expect it to at least observe the sort field of the resource selected

![image](https://user-images.githubusercontent.com/6242344/214825072-37a358cb-a82e-4388-a1e7-44fabeb4fbe5.png)

## Actual behavior

The options seem randomly sorted and there's no way to sort them.
![image](https://user-images.githubusercontent.com/6242344/214825445-e1d67feb-2154-4465-8923-f6460e4bd4be.png)

**Comment by jeffladiray** [comment]
We currently do not support ordering in dynamic simple configuration.
No sort is apply by default to retrieve the data required by Dynamic Simple Dropdown.

A potential workaround would be to use a Dynamic Smart Dropdown instead, allowing you to configure the order the way you want it.

I'm pushing this insight to our product board.

Thanks

**Comment by samtgarson** [comment]
Ok, thanks.
