### ISSUE TITLE
DummyDataSource raises "Column not found" error

### ISSUE THREAD

**Issue by tobiasdiez** [ForestAdmin/agent-nodejs#627]
## Expected behavior

No error.

## Actual behavior

```
 ERROR  Column not found: 'persons.authorId'                                                                        forestadmin 23:32:33

  at RelationCollectionDecorator.checkColumn (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\decorators\relation\collection.js:103:19)
  at RelationCollectionDecorator.checkKeys (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\decorators\relation\collection.js:91:37)
  at RelationCollectionDecorator.checkForeignKeys (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\decorators\relation\collection.js:76:41)
  at RelationCollectionDecorator.addRelation (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\decorators\relation\collection.js:15:14)
  at node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\collection-customizer.js:403:58
  at DecoratorsStack.applyQueuedCustomizations (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\decorators\decorators-stack.js:73:47)
  at async DataSourceCustomizer.getDataSource (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\datasource-customizer.js:114:9)
  at async node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\datasource-customizer.js:46:30
  at async DecoratorsStack.applyQueuedCustomizations (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\decorators\decorators-stack.js:73:13)
  at async DataSourceCustomizer.getDataSource (node_modules\.pnpm\@forestadmin+datasource-customizer@1.5.11\node_modules\@forestadmin\datasource-customizer\dist\datasource-customizer.js:114:9)
  at async Agent.start (node_modules\.pnpm\@forestadmin+agent@1.8.0\node_modules\@forestadmin\agent\dist\agent.js:56:28)
```

## Failure Logs

see above

## Context

Run 
```
createAgent({
    ...
  }).addDataSource(createDummyDataSource())
```

Example: https://github.com/tobiasdiez/nuxt-forestadmin/, run `pnpm install && pnpm dev`.

---
Background: Maybe the DummyDatasource is not the right tool for what I want. I would like to start a forestadmin backend with some test data, which I could then use for (integration) testing. I've seen that `https://api.development.forestadmin.com` is used in this repo for the forestServerUrl. Is this public? I have trouble accessing it.

**Comment by jeffladiray** [comment]
Hey @tobiasdiez :wave:

> I've seen that https://api.development.forestadmin.com is used in this repo for the forestServerUrl. Is this public? I have trouble accessing it.

No, we're using this URL for our own development setup, so ... not meant to be used (You can find more informations around our createAgent option [here](https://docs.forestadmin.com/developer-guide-agents-nodejs/getting-started/install/create-your-agent#forestserverurl-string-defaults-to-https-api.forestadmin.com)).

The dummy datasource is not meant to be used anymore (Thus, it is not documented). If you want to display dummy data only, you could use our typicode datasource (Not published but available on our `_example` project [here](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/_example/src/forest/datasources/typicode.ts))

If you want to have control over the models to create for your integration tests, you could also use the Sequelize/SQL datasource with an sqlite3 database.


Let me know if that helps 🙏

**Comment by tobiasdiez** [comment]
Thanks a lot for the quick reply!

> If you want to display dummy data only, you could use our typicode datasource (Not published but available on our `_example` project [here](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/_example/src/forest/datasources/typicode.ts))

This worked! Nice 🚀 

> No, we're using this URL for our own development setup, so ... not meant to be used (You can find more informations around our createAgent option [here](https://docs.forestadmin.com/developer-guide-agents-nodejs/getting-started/install/create-your-agent#forestserverurl-string-defaults-to-https-api.forestadmin.com)).

It's a bit of shame that there is no public testing environment. I've now setup a project on the main forestadmin website. Are there any security concerns of committing to github the auth and env secrets for this test project (with the data from typicode)?

**Comment by jeffladiray** [comment]
You can safely onboard using this test project by creating a new project in the UI, then directly use the AUTH_SECRET and ENV_SECRET variables given during the onboarding, if needed.

> It's a bit of shame that there is no public testing environment.

It really depends on what you want to achieve. We currently do not provide an environment for testing your app using the UI, however you should be able to generate multiple environment secret to create multiple testing environment if needed.

Again, `forestServerUrl` is not meant to be used, as the only allowed value is `api.forestadmin.com` (The default one), except in a very few use-case where this needs to be changed (Using our [on-premise stack](https://www.forestadmin.com/self-hosted)).

If you want to test our your agent using integration tests then indeed, we do not currently provide anything related.
I'll push this to our productboard.

I really hope it helps. If that's not the case, don't hesitate to share a bit more your use-case and what you are trying to achieve, I'm here to help :)

**Comment by tobiasdiez** [comment]
I'm developing an integration for [nuxt](https://nuxt.com/) at https://github.com/tobiasdiez/nuxt-forestadmin/, which is similar to the built-in integrations for say express. For this, I would like to have an easy setup to run integration and manual tests, to ensure that the integration is working as expected (e.g. cors is setup correctly, the correct routes are registered etc). I don't care about the actual data shown in the admin interface. But, ideally, other contributors could work on the nuxt integration without even having their own forestadmin account. For now, I've followed your advice and registered a new project and specify the env/auth secret for it. This works for myself, but gets a bit awkward once someone else wants to contribute to the nuxt integration.

Anyway, the original issue I had is resolved. I let you decide if you want to keep this issue open until the dummy datasource is removed (if that's your plan) or just close it.
