### ISSUE TITLE
Postgresql views should be displayed

### ISSUE THREAD

**Issue by james075** [ForestAdmin/agent-nodejs#651]
## Expected behavior

Postgresql views should be found in the generated `.forestadmin-schema.json` file. What did I miss ?

## Actual behavior

`addDataSource` doesn't take into account PostgreSQL views, `.forestadmin-schema.json` contains only tables

The implementation is pretty simple
```ts
import { createAgent } from '@forestadmin/agent';
import { createSqlDataSource } from '@forestadmin/datasource-sql';

await createAgent({
    authSecret: configService.get<string>('back-office.forest.authSecret'),
    envSecret: configService.get<string>('back-office.forest.envSecret'),
    isProduction: configService.get<string>('back-office.env') === 'production',
  })
    .addDataSource(createSqlDataSource(configService.get<string>('back-office.databaseUrl')))
    .mountOnNestJs(app)
    .start();

```

## Context

PostgreSQL 13

```json
{
  "@forestadmin/agent": "^1.8.5",
  "@forestadmin/datasource-sql": "^1.2.8",
  "@nestjs/common": "^9.3.10",
  "@nestjs/config": "^2.3.1",
  "@nestjs/core": "^9.3.10",
  "@nestjs/platform-express": "^9.3.10",
  "class-transformer": "^0.5.1",
  "class-validator": "^0.14.0",
  "pg": "^8.10.0",
  "reflect-metadata": "^0.1.13",
  "rimraf": "^4.4.0",
  "rxjs": "^7.8.0",
  "ts-pattern": "^4.2.1",
  "uuid": "^9.0.0"
}
```

**Comment by jeffladiray** [comment]
Hey :wave:

Currently, Postgres views aren't supported by the SQL Datasource. the SQL Datasource was developed with the full CRUD support in mind, thus aren't not compatible with it.

You can implement them using our Sequelize datasource in combination with the SQL one, but this requires you to define Sequelize models associated with your view.
You can find more info about this in our [Sequelize datasource documentation](https://docs.forestadmin.com/developer-guide-agents-nodejs/data-sources/provided-data-sources/sequelize).

I'm pushing this as a feature suggestion in our productboard.

Let me know if that helps.

**Comment by okomarov** [comment]
@jeffladiray Nice pointer. I think it might be useful to clarify that on https://docs.forestadmin.com/documentation/extra-help/databases/manage-sql-views and point to your link so we can de fact add multiple data sources (if I understood correctly)

**Comment by jeffladiray** [comment]
Hey @okomarov :wave:

For this agent, the documentation can be found [here](https://docs.forestadmin.com/developer-guide-agents-nodejs/).
But indeed you are right, there are currently no documentation regarding this use case. We tend to think that this is not the greatest way to handle SQL views at the moment (As you are forced to use a Sequelize datasource, thus write your models for your view) so ... This is more a workaround than an actual solution - and that's mainly why this isn't currently documented for this new agent (And that's also why this issue isn't closed).

Thanks for your feedback !

**Comment by jeffladiray** [comment]
Hey :wave: 

Sorry for the delayed response.

Did you check the visibility of the collection? (Collections are hidden by default, you need to manually mark them as visible)
Eventually, did you try to run a `sequelize.query` to check that everything is all settled correctly.

From the code you share, everything should be working as expected on developement.

In the future, and if you want a "quicker" assistance, you can reach out to us via [our community](https://community.forestadmin.com/). Our technical team answers way faster there.
