### ISSUE TITLE
Error on Search in UI interface: Unrecognized expression '$toString'

### ISSUE THREAD

**Issue by Iulian-Dragomirescu** [ForestAdmin/agent-nodejs#871]
This happens when I press enter in the search bar in the Ui interface. Any Ideea?

Error from? mongoose? forest-admin?

i try oldest version (all 3, mongoose forest-admin and forest mongoose..) but still same error..

```
===== An exception was raised =====
GET /Table?{
 timezone: Europe/Bucharest,
 fields[Table]: name,codp,lowest_price,galatek_price,agropro_price,expert_scule_price,magazia_lui_costica_price,tehnomart_price,
 isSearchExtended: false,
 page[number]: 1,
 page[size]: 15,
 search: fd,
 searchExtended: 0,
 sort: -_id
}

 Unrecognized expression '$toString'

MongoServerError: Unrecognized expression '$toString'
    at Connection.onMessage (C:\xyz\node_modules\mongodb\lib\cmap\connection.js:202:26)
[...]
===================================
```

**Comment by ShohanRahman** [comment]
Hi @Iulian-Dragomirescu ,

Could you please create a topic about your issue on our community forum ?

([here it is the forum link](https://community.forestadmin.com/c/help-me/))

It will be easier for our team to help you and it might help futur users if they encounter the same issue.

Best regards,

Shohan

**Comment by romain-gilliotte** [comment]
Hi @Iulian-Dragomirescu 

Your agent is using the $toString operator, which is only supported only [since Mongo 4.0
](https://www.mongodb.com/docs/manual/reference/operator/aggregation/#type-expression-operators)

You are probably using an older version of Mongo.

**Comment by Iulian-Dragomirescu** [comment]
Hi, actually, it solved itself =) I had all the updated versions at that time
