### ISSUE TITLE
High severity vulnerability in @forestadmin/agent because of @koa/cors dependency

### ISSUE THREAD

**Issue by xiniria** [ForestAdmin/agent-nodejs#896]
An [overly permissive origin policy vulnerability](https://github.com/advisories/GHSA-qxrj-hx23-xp82) has been discovered in versions [`@koa/cors`](https://github.com/koajs/cors), and fixed in version `5.0.0` ([source](https://github.com/koajs/cors/commit/f31dac99f5355c41e7d4dd3c4a80c5f154941a11)). `@forestadmin/agent` uses version `4.0.0` of `@koa/cors`, the package should be updated to remove the vulnerability.

- Package Version: all

**Comment by ghusse** [comment]
Hello @xiniria,

Thanks for the info. We'll test the new version to make sure it does not break anything and we'll release a patch on the agent.

**Comment by xiniria** [comment]
@ghusse I can take a look at it if you want, but I don't know if the test pipeline is enough to make sure an update doesn't break anything; or do you have any way to test updates locally?

**Comment by ghusse** [comment]
I think that for this one we need to check that the browser is accepting answers from the agent, when deployed with this new package. There is a change in the behavior when upgrading from v4 to v5, and I don't think we can check it automatically.

We're on it, the fix should be released in the coming days.

**Comment by xiniria** [comment]
Thanks a lot for your responsiveness

**Comment by ghusse** [comment]
Hello @xiniria,

We merged the PR #897 after validating that everything was working great with this upgrade. The fix has been released, and I invite you to upgrade to the latest version of the different packages you are using.
